# Generated by Django 5.0 on 2024-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0002_delete_menuitem_customer_number_of_pax_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
