# Generated by Django 5.0 on 2024-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0003_remove_customer_id_alter_customer_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "admin_id",
                    models.CharField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("admin_name", models.CharField(max_length=100)),
                ("admin_phone_number", models.CharField(max_length=15, unique=True)),
                ("admin_email", models.EmailField(max_length=255, unique=True)),
                ("admin_password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("SuperAdmin", "SuperAdmin")],
                        default="Admin",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("staff_name", models.CharField(max_length=100)),
                ("staff_phone_number", models.CharField(max_length=15, unique=True)),
                ("staff_email", models.EmailField(max_length=255, unique=True)),
                ("staff_password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Staff", "Staff")],
                        default="Staff",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
        ),
    ]
