# Generated by Django 5.0 on 2024-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0004_admin_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={},
        ),
        migrations.RenameField(
            model_name="admin",
            old_name="admin_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="admin",
            old_name="admin_password",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="staff_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="staff_password",
            new_name="password",
        ),
        migrations.AlterField(
            model_name="admin",
            name="role",
            field=models.CharField(default="Admin", max_length=20),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(default="Staff", max_length=10),
        ),
    ]
