# Generated by Django 5.0 on 2024-10-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0005_alter_admin_options_alter_staff_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_image",
            field=models.ImageField(blank=True, null=True, upload_to="staff_images/"),
        ),
    ]
