# Generated by Django 5.0 on 2024-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0006_staff_staff_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "menu_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("menu_name", models.CharField(max_length=100)),
                (
                    "menu_image",
                    models.ImageField(blank=True, null=True, upload_to="menu_images/"),
                ),
                ("menu_description", models.CharField(max_length=200)),
                ("menu_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("menu_availability", models.CharField(max_length=50)),
            ],
        ),
    ]
