# Generated by Django 5.0 on 2024-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0009_rename_cust_id_order_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="menu_items",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
