# Generated by Django 5.0 on 2024-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0012_order_payment_method_alter_order_menu_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.ImageField(default="Empty", upload_to="receipts/"),
        ),
    ]
