# Generated by Django 5.0 on 2024-10-12 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0013_order_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.ImageField(upload_to="receipts/"),
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_method", models.CharField(max_length=50)),
                ("status", models.CharField(default="Completed", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queuingsystem.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queuingsystem.order",
                    ),
                ),
            ],
        ),
    ]
