# Generated by Django 5.0 on 2024-10-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0019_alter_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderhistory",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderHistory",
        ),
    ]
