# Generated by Django 5.0 on 2024-10-12 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0020_remove_orderhistory_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("menu_items", models.JSONField(default=dict)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "date_ordered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default="QR Code", max_length=50, null=True
                    ),
                ),
                ("receipt", models.ImageField(upload_to="receipts/")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queuingsystem.customer",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="queuingsystem.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_method", models.CharField(max_length=50)),
                ("status", models.CharField(default="Completed", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queuingsystem.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queuingsystem.order",
                    ),
                ),
            ],
        ),
    ]
