# Generated by Django 5.0 on 2024-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0023_alter_order_payment_method_delete_orderhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
