# Generated by Django 5.0 on 2024-10-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0024_order_table_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
