# Generated by Django 5.0 on 2024-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0026_order_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_verified",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
