# Generated by Django 5.0 on 2024-10-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queuingsystem", "0028_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
